"""add telegram_connect_token

Revision ID: 060b27679745
Revises: 9581d49132c6
Create Date: 2026-08-13 13:29:50.353301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060b27679745'
down_revision: Union[str, Sequence[str], None] = '9581d49132c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'shares',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    op.alter_column('transactions', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.add_column('users', sa.Column('telegram_connect_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_telegram_connect_token'), 'users', ['telegram_connect_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_connect_token'), table_name='users')
    op.drop_column('users', 'telegram_connect_token')
    op.alter_column('transactions', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('transactions', 'shares',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    # ### end Alembic commands ###
