"""add target_price and alert_triggered to watchlist

Revision ID: 17a5362a4f2a
Revises: 060b27679745
Create Date: 2026-08-16 17:53:43.243875

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '17a5362a4f2a'
down_revision: str | Sequence[str] | None = '060b27679745'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
