"""add telegram_id to users

Revision ID: 620ff94539f5
Revises: 
Create Date: 2026-08-11 15:13:01.152484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620ff94539f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE transactions SET shares = 0 WHERE shares IS NULL")
    op.execute("UPDATE transactions SET price = 0 WHERE price IS NULL")
    op.alter_column('transactions', 'shares',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    op.alter_column('transactions', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # op.add_column('users', sa.Column('telegram_id', sa.String(length=50), nullable=True))
    # op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_column('users', 'telegram_id')
    op.alter_column('transactions', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('transactions', 'shares',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    # ### end Alembic commands ###



# alembic upgrade head

# alembic revision --autogenerate -m "add telegram_id to users"
# יוצר קובץ ל version חדש 
