"""add alert in watchlist

Revision ID: d09bb1956ab4
Revises: 17a5362a4f2a
Create Date: 2026-08-16 20:16:47.200573

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd09bb1956ab4'
down_revision: str | Sequence[str] | None = '17a5362a4f2a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('target_price', sa.Float(), nullable=True))
    op.add_column('watchlist', sa.Column('alert_triggered', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('watchlist', sa.Column('alert_direction', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'alert_direction')
    op.drop_column('watchlist', 'alert_triggered')
    op.drop_column('watchlist', 'target_price')
    # ### end Alembic commands ###
